version: '3.4'
services:
  owl-music-bot-db:
    container_name: mysql
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - webnet
  owl-music-bot:
    container_name: owl-music-bot
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start
    networks:
      - webnet

networks:
  webnet:

volumes:
  db-vol: